// <auto-generated />
using System;
using IdentityBlazorCoreAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IdentityBlazorCoreAPI.Data.Migrations
{
    [DbContext(typeof(IdentityBlazorCoreAPIDbContext))]
    [Migration("20240729204410_User_PublishAt")]
    partial class User_PublishAt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("IdentityBlazorCoreAPI.Data.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Biography")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("BirthDay")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "OWNER-AUGCENTER-2023",
                            AccessFailedCount = 0,
                            Address = "",
                            Biography = "",
                            ConcurrencyStamp = "dccf21e0-06e4-45cc-85a2-0a31984e8320",
                            Email = "owner@augcenter.com",
                            EmailConfirmed = false,
                            FirstName = "Aug",
                            Gender = "",
                            LastName = "Center",
                            LockoutEnabled = false,
                            NormalizedEmail = "OWNER@AUGCENTER.COM",
                            NormalizedUserName = "OWNER@AUGCENTER.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEG+Ux58SADLpnjwEm/l2lvhCaCYNa2DcDURXI5yYETwGH/xGb6w2fVnAp1IkHEv5hw==",
                            PhoneNumber = "0868752251",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b963d7cf-e7d1-4384-8710-aff8ee6e73dc",
                            TwoFactorEnabled = false,
                            UserName = "owner@augcenter.com"
                        },
                        new
                        {
                            Id = "ADMIN-AUGCENTER-2023",
                            AccessFailedCount = 0,
                            Address = "",
                            Biography = "",
                            ConcurrencyStamp = "38fdaf70-85c2-4e70-9736-632982888336",
                            Email = "administructor@augcenter.com",
                            EmailConfirmed = false,
                            FirstName = "Aug",
                            Gender = "",
                            LastName = "Center",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMINISTRUCTOR@AUGCENTER.COM",
                            NormalizedUserName = "ADMINISTRUCTOR@AUGCENTER.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEI1hNaWINV3swQvF26efn5r54ChqtGHoqEcptTbWedriPvSJLVsPIsbA+OI6BPLx7Q==",
                            PhoneNumber = "0868752251",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ac9e7b1c-02cd-4404-bdb3-0297939cb40e",
                            TwoFactorEnabled = false,
                            UserName = "administructor@augcenter.com"
                        },
                        new
                        {
                            Id = "SELLER-AUGCENTER-2023",
                            AccessFailedCount = 0,
                            Address = "",
                            Biography = "",
                            ConcurrencyStamp = "4d79e0d2-a3ee-4a01-9990-42d50092b473",
                            Email = "seller@augcenter.com",
                            EmailConfirmed = false,
                            FirstName = "Aug",
                            Gender = "",
                            LastName = "Center",
                            LockoutEnabled = false,
                            NormalizedEmail = "SELLER@AUGCENTER.COM",
                            NormalizedUserName = "SELLER@AUGCENTER.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEFpjWwe80o67Zzte/7KhTpi1JE2rfRAxjg5wAwShvCxkdzTfUornNipUDZnU8KrgPQ==",
                            PhoneNumber = "0868752251",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "98115bfe-d9f5-4291-a8ed-ef87345551a3",
                            TwoFactorEnabled = false,
                            UserName = "seller@augcenter.com"
                        },
                        new
                        {
                            Id = "BUYER-AUGCENTER-2023",
                            AccessFailedCount = 0,
                            Address = "",
                            Biography = "",
                            ConcurrencyStamp = "07f27a7f-e4f5-45d1-8c09-053d65730a68",
                            Email = "buyer@augcenter.com",
                            EmailConfirmed = false,
                            FirstName = "Aug",
                            Gender = "",
                            LastName = "Center",
                            LockoutEnabled = false,
                            NormalizedEmail = "BUYER@AUGCENTER.COM",
                            NormalizedUserName = "BUYER@AUGCENTER.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEDS5OTDqWOmJX7pmFmE7pin25vSHuS+ys+uO60MPCIqO0gHTFOD7c+xF5N7T+3DNrQ==",
                            PhoneNumber = "0868752251",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "892b92ac-21d5-4cdf-b97f-30190873b01c",
                            TwoFactorEnabled = false,
                            UserName = "buyer@augcenter.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            ConcurrencyStamp = "30/07/2024 3:44:07 SA",
                            Name = "Owner",
                            NormalizedName = "OWNER"
                        },
                        new
                        {
                            Id = "2",
                            ConcurrencyStamp = "30/07/2024 3:44:07 SA",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRUCTOR"
                        },
                        new
                        {
                            Id = "3",
                            ConcurrencyStamp = "30/07/2024 3:44:07 SA",
                            Name = "Manager",
                            NormalizedName = "MANAGER"
                        },
                        new
                        {
                            Id = "4",
                            ConcurrencyStamp = "30/07/2024 3:44:07 SA",
                            Name = "Seller",
                            NormalizedName = "SELLER"
                        },
                        new
                        {
                            Id = "5",
                            ConcurrencyStamp = "30/07/2024 3:44:07 SA",
                            Name = "Buyer",
                            NormalizedName = "BUYER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "OWNER-AUGCENTER-2023",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "ADMIN-AUGCENTER-2023",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "SELLER-AUGCENTER-2023",
                            RoleId = "4"
                        },
                        new
                        {
                            UserId = "BUYER-AUGCENTER-2023",
                            RoleId = "5"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("IdentityBlazorCoreAPI.Data.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("IdentityBlazorCoreAPI.Data.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IdentityBlazorCoreAPI.Data.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("IdentityBlazorCoreAPI.Data.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
